### ISSUE TITLE
Broken on Lumen 5.4 from PR #16

### ISSUE THREAD

**Issue by jon-frankel** [dusterio/laravel-plain-sqs#17]
PR #16 caused our installation of Lumen 5.4.7 to fail. The version string returned by `$this->container->version()` is `"Lumen (5.4.7) (Laravel Components 5.4.*)"`. But if you do

```>>> version_compare("Lumen (5.4.7) (Laravel Components 5.4.*)", '5.4')```

this returns `-1`. So the update to this conditional doesn't work properly in this case. I'm currently reverting to the previous 0.1.8 tag.

**Comment by dusterio** [comment]
I'll revert back to regular expression instead of version_compare() shortly, thanks for reporting

**Comment by dusterio** [comment]
I'm tagging a new release, I brought back the regexp

**Comment by jon-frankel** [comment]
Thanks!
