### ISSUE TITLE
Create new tag with the recent bug fixes

### ISSUE THREAD

**Issue by adriaPerez** [dusterio/laravel-plain-sqs#22]
Significant bug fixes such as #21 were added but without a new tag those can't be moved to our projects (composer doesn't detect a newer version).

@dusterio  Can you please create a new release?

**Comment by carpendisa** [comment]
bump!

**Comment by luisdalmolin** [comment]
@dusterio can we tag a new release with latest fixes? Would really help. And thanks for your work on this package.

**Comment by dusterio** [comment]
@luisdalmolin sure, done!
