### ISSUE TITLE
Handle countable exception

### ISSUE THREAD

**Issue by carpendisa** [dusterio/laravel-plain-sqs#23]
count(): Parameter must be an array or an object that implements Countable {"exception":"[object] (ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable at ...vendor/dusterio/laravel-plain-sqs/src/Sqs/Queue.php:65

@dusterio

**Comment by briedis** [comment]
OK, I just encountered this randomly after updating to PHP 7.2.

What was the solution? Was this fixed in a later version?
