### ISSUE TITLE
undefined index key (Connector.php)

### ISSUE THREAD

**Issue by 4l3j4ndr0** [dusterio/laravel-plain-sqs#52]
I have an error when use the library on aws ec2 machine with iam rol execution.
![image](https://user-images.githubusercontent.com/18580284/151644254-d71b34d9-66c9-47d6-9437-5204b0e58cc9.png)

The error is on Connector.php line 22.

i solved this in pull request https://github.com/dusterio/laravel-plain-sqs/pull/51

**Comment by dusterio** [comment]
@4l3j4ndr0 thanks, this makes sense
