### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by drekinov** [dusterio/laravel-plain-sqs#60]
laravel 10 is officially released.
can we bump composer.json

**Comment by erikaraujo** [comment]
@dusterio I created a PR that takes care of adding the compatibility and also including version `10` on the `Queue` regex.

**Comment by robertheydenrych** [comment]
I am in the process of upgrading a Laravel project to v10 and ran into this issue to. This package is starting to look like it's no inactive.

**Comment by norivaltoniato** [comment]
@dusterio any chance of merging this PR?
