### ISSUE TITLE
Call to undefined method createJobsUsing

### ISSUE THREAD

**Issue by NomikOS** [dusterio/laravel-plain-sqs#7]
When I run 

`artisan queue:listen`

I have:

`PHP Fatal error:  Call to undefined method Dusterio\PlainSqs\Sqs\Queue::createJobsUsing() in vendor/dusterio/laravel-plain-sqs/src/Sqs/Connector.php on line 30`

---

This method `createJobsUsing` was removed after a refactorizarion:
https://github.com/laravel/framework/commit/8952983cab6b45363e3e9d7484dc899a3288186c#diff-6259ad5540e1bc11f8d7a47e3439f8ccL132

Any suggestion?
Thanks.-

**Comment by dusterio** [comment]
Hmm, so it's a 5.3 issue? I will fix this shortly then

**Comment by NomikOS** [comment]
Yes, In 5.2.1 (lumen) works well.

**Comment by dusterio** [comment]
Can you try now please? I tested both in 5.2 and 5.3 and it works for me

**Comment by NomikOS** [comment]
Yes, it works now. Thanks.-
