### ISSUE TITLE
Compatability to Laravel 11

### ISSUE THREAD

**Issue by agilan-selvam-zoomrx** [dusterio/laravel-plain-sqs#71]
Hi,

We are planning to upgrade our application from Laravel 10 to Laravel 11. For that, We want to know, when the compatability for Laravel 11 will be released for this library.

It would be helpful, if you reply.

Thanks in advance.

**Comment by alexw23** [comment]
(https://github.com/dusterio/laravel-plain-sqs/pull/67) has been merged

**Comment by agilan-selvam-zoomrx** [comment]
Thank you so much @alexw23
